defmodule A2aAgentWebWeb.SummarizerControllerTest do
  @moduledoc """
  Tests for the SummarizerController summarization endpoint.
  """
  use A2aAgentWebWeb.ConnCase, async: true

  @doc """
  POST /api/summarize returns a summary for customer feedback.
  """
  test "POST /api/summarize returns summary", %{conn: conn} do
    feedback = "The product is great but the delivery was slow."
    conn = post(conn, "/api/summarize", %{text: feedback})
<<<<<<< HEAD
    summary = json_response(conn, 200)["summary"]
    assert is_binary(summary)
    assert String.length(summary) > 0
  end

  @doc """
  POST /api/story returns a story generated by the LLM.
  """
  test "POST /api/story returns story", %{conn: conn} do
    prompt = "A robot wanted to learn Elixir."
    conn = post(conn, "/api/story", %{text: prompt})
    story = json_response(conn, 200)["story"]
    assert is_binary(story)
    assert String.length(story) > 0
=======
    assert json_response(conn, 200)["summary"] =~ "product"
>>>>>>> 2eee8fe (feat: multi-agent orchestration, OpenAI summarizer agent, new endpoints, improved diagrams, and docs. Fixes, tests, and operator/agent extensibility.)
  end
end
